services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: seniorproject-api
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: seniorproject-client
    ports:
      - "3000:80"

volumes:
  postgres_data: