from enum import Enum


class Permissions(Enum):
    # ORGANIZATIONS
    VIEW_ALL_ORGANIZATIONS = 1
    VIEW_CURRENT_ORGANIZATION = 2
    VIEW_SPECIFIC_ORGANIZATION = 3
    CREATE_NEW_ORGANIZATION = 4
    UPDATE_CURRENT_ORGANIZATION = 5
    UPDATE_ALL_ORGANIZATIONS = 6
    DELETE_ORGANIZATION = 7
    # PEOPLE
    VIEW_ALL_PEOPLE = 8
    VIEW_ALL_CURRENT_ORG_PEOPLE = 9
    VIEW_ALL_CURRENT_ORG_EMPLOYEE = 10
    VIEW_ALL_CURRENT_ORG_PATIENTS = 11
    UPDATE_ALL_PEOPLE = 12
    UPDATE_CURRENT_ORG_PEOPLE = 13

    CREATE_ALL_PEOPLE = 14
    CREATE_CURRENT_ORG_PEOPLE = 16
    CREATE_BASE_USER = 15

    DELETE_ALL_PEOPLE = 17
    DELETE_CURRENT_ORG_PEOPLE = 18

    # MESSAGES
    VIEW_ALL_MESSAGES = 19
    VIEW_ALL_CURRENT_ORG_MESSAGES = 20
    VIEW_ALL_CURRENT_LOCATION_MESSAGES = 21
    SEND_ANNOUNCEMENT = 22
    SEND_MESSAGE = 23

    # LOCATIONS
    DELETE_ALL_LOCATIONS = 24
    DELETE_CURRENT_ORG_LOCATIONS = 25
    VIEW_ALL_LOCATIONS = 26
    VIEW_ALL_CURRENT_ORG_LOCATIONS = 28
    VIEW_CURRENT_LOCATION = 29
    CREATE_NEW_LOCATION = 30
    CREATE_NEW_LOCATION_SUPERADMIN = 31
    UPDATE_CURRENT_LOCATION = 32
    UPDATE_ALL_LOCATIONS = 33
