from enum import Enum

class Permissions(Enum):
    VIEW_ALL_ORGANIZATIONS = 1
    VIEW_CURRENT_ORGANIZATION = 2
    VIEW_SPECIFIC_ORGANIZATION = 3
    CREATE_NEW_ORGANIZATION = 4
    UPDATE_CURRENT_ORGANIZATION = 5
    UPDATE_ALL_ORGANIZATIONS = 6
    DELETE_ORGANIZATION = 7

    VIEW_ALL_PEOPLE = 8
    VIEW_ALL_CURRENT_ORG_PEOPLE = 9
    VIEW_ALL_CURRENT_ORG_EMPLOYEE = 10 
    VIEW_ALL_CURRENT_ORG_PATIENTS= 11

    VIEW_ALL_MESSAGES = 12
    VIEW_ALL_CURRENT_ORG_MESSAGES = 13
    VIEW_ALL_CURRENT_LOCATION_MESSAGES = 14
    SEND_ANNOUNCEMENT = 15