from enum import Enum

class Permissions(Enum):
    #ORGANIZATIONS
    VIEW_ALL_ORGANIZATIONS = 1
    VIEW_CURRENT_ORGANIZATION = 2
    VIEW_SPECIFIC_ORGANIZATION = 3
    CREATE_NEW_ORGANIZATION = 4
    UPDATE_CURRENT_ORGANIZATION = 5
    UPDATE_ALL_ORGANIZATIONS = 6
    DELETE_ORGANIZATION = 7
    #PEOPLE
    VIEW_ALL_PEOPLE = 8
    VIEW_ALL_CURRENT_ORG_PEOPLE = 9
    VIEW_ALL_CURRENT_ORG_EMPLOYEE = 10 
    VIEW_ALL_CURRENT_ORG_PATIENTS= 11
    #MESSAGES
    VIEW_ALL_MESSAGES = 12
    VIEW_ALL_CURRENT_ORG_MESSAGES = 13
    VIEW_ALL_CURRENT_LOCATION_MESSAGES = 14
    #LOCATIONS
    VIEW_ALL_LOCATIONS = 20
    VIEW_ALL_CURRENT_ORG_LOCATIONS = 21
    VIEW_CURRENT_LOCATION = 22
    CREATE_NEW_LOCATION = 23
    UPDATE_CURRENT_LOCATION = 24
    UPDATE_ALL_LOCATIONS = 25
    DELETE_LOCATION = 26